#!/usr/bin/env ruby

require 'webrick'
include WEBrick

def start_webrick(config = {})
  config.update(:Port => 8080)     
  server = HTTPServer.new(config)
  yield server if block_given?
  ['INT', 'TERM'].each {|signal| 
    trap(signal) {server.shutdown}
  }
  server.start

end

start_webrick {|server|
  doc_root = './'
  server.mount("/", HTTPServlet::FileHandler, doc_root, {:FancyIndexing=>true})
}
